// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASeJLxSIBURl86J4aGLAM5Cxjed-d_6wU',
    appId: '1:162827959233:web:0ba58a0400180baae64d40',
    messagingSenderId: '162827959233',
    projectId: 'study-app-aa7fb',
    authDomain: 'study-app-aa7fb.firebaseapp.com',
    storageBucket: 'study-app-aa7fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSnOU7fRP_ktk0-jWZAgkVIynZTdWlxw',
    appId: '1:162827959233:android:aec31ad2149902cde64d40',
    messagingSenderId: '162827959233',
    projectId: 'study-app-aa7fb',
    storageBucket: 'study-app-aa7fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbB8GIwA7hYPUt3Ju_aZ_UE5HdpImRMvI',
    appId: '1:162827959233:ios:501a4dc982c7d8f8e64d40',
    messagingSenderId: '162827959233',
    projectId: 'study-app-aa7fb',
    storageBucket: 'study-app-aa7fb.appspot.com',
    iosClientId: '162827959233-mlpkjqn46nd0kq8f4na71jtlm74oh1rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbB8GIwA7hYPUt3Ju_aZ_UE5HdpImRMvI',
    appId: '1:162827959233:ios:501a4dc982c7d8f8e64d40',
    messagingSenderId: '162827959233',
    projectId: 'study-app-aa7fb',
    storageBucket: 'study-app-aa7fb.appspot.com',
    iosClientId: '162827959233-mlpkjqn46nd0kq8f4na71jtlm74oh1rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
